### ISSUE TITLE
Incompatible with relay-compiler version 9?

### ISSUE THREAD

**Issue by a-sane** [zth/relay-compiler-language-js-flow-uncommented#1]
Error: Cannot find module 'relay-compiler/lib/RelayFlowGenerator'

Maybe this can help: https://github.com/relay-tools/relay-compiler-language-typescript/issues/151

**Comment by zth** [comment]
Hey! I don't maintain this anymore, but I believe Relay now ships its own Flow types, no?
https://github.com/facebook/relay/blob/b065ae242fd24387dc14195f00d693615c2e7b81/gulpfile.js#L256-L268

**Comment by a-sane** [comment]
In last relay version (9.1.0) generated flow types in `__generated__` folders still commented and WebStorm/IDEA do not properly support flow types inside of comments.
Also your plugin still mentioned in actual docs: https://relay.dev/docs/en/type-emission#language-plugins
So it seems in that case I should create issue in relay repo about their docs :)
Thank you!

**Comment by zth** [comment]
If you're interested in having this work, it's probably pretty easy to solve and I'd be happy to merge a PR for it! @a-sane would you be interested in doing a PR?

**Comment by a-sane** [comment]
@zth sure, i think this should fix the issue:
https://github.com/zth/relay-compiler-language-js-flow-uncommented/pull/2
I checked on my project, and it seems to be working well

**Comment by zth** [comment]
@a-sane excellent, thank you! I will release a new version ASAP. Thanks for fixing this 😄

**Comment by zth** [comment]
@a-sane out in `2.0.0` 🎉

**Comment by a-sane** [comment]
@a-sane amazing, thank you!
